name: Lint and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    
    # This sets the working directory for all steps in this job
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm' # Caches dependencies to speed up future runs
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install Dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint
